deployment:
  tasks:
    - /bin/bash -lc 'echo "[cpanel] setting NODE_ENV=production" && export NODE_ENV=production'

    - /bin/bash -lc 'echo "[cpanel] Installing server dependencies (root package.json)" && npm ci'

    # 👇 Fix permissions for node_modules/.bin tools
    - /bin/bash -lc 'chmod +x node_modules/.bin/*'

    - /bin/bash -lc 'echo "[cpanel] Building TypeScript server" && npm run build'

    - /bin/bash -lc 'echo "[cpanel] Installing client dependencies" && cd client && npm ci'

    - /bin/bash -lc 'echo "[cpanel] Building client (Vite)" && cd client && npm run build'

    - /bin/bash -lc 'echo "[cpanel] Ensuring public_html exists and copying built client files" && mkdir -p "$HOME/public_html" && cp -r client/dist/* "$HOME/public_html/"'

  restart: true
